### ISSUE TITLE
Empty dataset

### ISSUE THREAD

**Issue by Scalsol** [yuan-xiaohan/4D-Myocardium-Reconstruction-with-Decoupled-Motion-and-Shape-Model#1]
Hi authors, thanks for sharing the code! But it seems the google folder is empty. Could you help fixing the issue? Thanks!

**Comment by yuan-xiaohan** [comment]
The data has been uploaded and you can download it according to the requirements. Thank you for following our work!

**Comment by Scalsol** [comment]
Hi, I have sent the request a few days ago, could you check and approve it? Thanks!

**Comment by yuan-xiaohan** [comment]
Dear Yihong,

I'm sorry for not being able to respond promptly. We have added ***@***.*** to the shared list. Please check it. 
If you have any questions, feel free to contact us. Thank you for your attention to our work!


Best regards,
Xiaohan Yuan










At 2023-10-09 03:35:50, "Yihong Chen" ***@***.***> wrote:

Hi, I have sent the request a few days ago, could you check and approve it? Thanks!

**Comment by Scalsol** [comment]
Dear Xiaohan,

Thanks very much! I checked the data and it seems for each sequence it contains an `/image` and `/mesh` folder. But according to the README it should also contain `P.txt` and folder `/points` or the script `preprocess_data.py` will not be able to execute (it I understand correctly). So I want to ask will you provide the `P.txt` and `/points`, or could you tell me the process to obtain the transformation matrix and the point clouds?

Thanks in advance!

**Comment by yuan-xiaohan** [comment]
Dear Yihong,
Thank you for your question. We currently only provide the original files. Based on your suggestion, we will consider uploading 'P.txt' and '/points' as preprocessing data for easier use. We will notify you once this is done.




Best regards,
Xiaohan Yuan










At 2023-10-10 22:02:46, "Yihong Chen" ***@***.***> wrote:

Dear Xianhan,

Thanks very much! I checked the data and it seems for each sequence it contains an /image and /mesh folder. But according to the README it should also contain P.txt and folder /points or the script preprocess_data.py will not be able to execute (it I understand correctly). So I want to ask will you provide the P.txt and /points, or could you tell me the process to obtain the transformation matrix and the point clouds?

Thanks in advance!

**Comment by yuan-xiaohan** [comment]
All P.txt files have been uploaded. Please review them. If you have any questions, please let us know. Thank you.
