### ISSUE TITLE
Data preprocessing steps in my dataset.

### ISSUE THREAD

**Issue by RespectKnowledge** [yuan-xiaohan/4D-Myocardium-Reconstruction-with-Decoupled-Motion-and-Shape-Model#2]
Dear Author, Thanks for sharing the code. I have issued to use your method in my dataset. I have input, segmentation and I can generate meshes from segmentation. According to demo you mention as shown below, P.text file and points, But I missing these files from your dataset. How Can I get these two files from your dataset and secondly How can I prepare these two in my dataset. Thanks in advance
|-- data
        # Data to be processed.
        P.txt
        # Matrix used for converting to ED shape space.
        |-- mesh
            # You can get the surface meshes from our dataset link. 
        |-- points
            # 3D surface points obtained from segmentation. 
            |-- 00.obj
            ...
            |-- 24.obj

**Comment by yuan-xiaohan** [comment]
Thank you for your interest in our work! All P.txt files have been uploaded. Please review.
