### ISSUE TITLE
Missing Data for Preprocessing

### ISSUE THREAD

**Issue by abdulkaderghandoura** [yuan-xiaohan/4D-Myocardium-Reconstruction-with-Decoupled-Motion-and-Shape-Model#3]
Dear Xiaohan,

Thank you for sharing the code and data. As discussed by the others, since the `points/` directories are required to execute `preprocess_data.py`, will you also upload them? If not, please share the code to obtain them with the arguments explained.

Best regards,
Abdulkader

**Comment by yuan-xiaohan** [comment]
Based on your suggestion, we have added points files to the dataset directory for you to view and download. You will see that each point cloud file consists of several "wireframes," with each wireframe being the cross-section of the mesh at each MRI slice position.
